package batch

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/ytp24/ytp24/pkg/core"
	"github.com/ytp24/ytp24/pkg/validator"
)

// ConcurrentBatchEngine implements core.BatchProcessor using a managed Worker Pool.
type ConcurrentBatchEngine struct {
	extractor core.Extractor
}

// NewConcurrentBatchEngine initializes a new ConcurrentBatchEngine.
func NewConcurrentBatchEngine(ext core.Extractor) *ConcurrentBatchEngine {
	return &ConcurrentBatchEngine{extractor: ext}
}

// ProcessBatch runs concurrent worker goroutines to process PDF files in parallel.
func (b *ConcurrentBatchEngine) ProcessBatch(
	ctx context.Context,
	pdfFiles []string,
	targetBaseDir string,
	batchName string,
	concurrency int,
	reporter core.ProgressReporter,
) (*core.BatchResult, error) {
	if len(pdfFiles) == 0 {
		return nil, fmt.Errorf("no PDF files provided for batch processing")
	}

	startTime := time.Now()

	if strings.TrimSpace(batchName) == "" {
		batchName = "batch"
	}

	cleanBaseDir := validator.ExpandPath(targetBaseDir)
	batchTargetDir := filepath.Join(cleanBaseDir, batchName)
	if err := os.MkdirAll(batchTargetDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create batch directory '%s': %w", batchTargetDir, err)
	}

	if concurrency <= 0 {
		concurrency = runtime.NumCPU()
		if concurrency < 2 {
			concurrency = 2
		}
		if concurrency > 8 {
			concurrency = 8
		}
	}

	totalFiles := len(pdfFiles)

	type job struct {
		path string
	}

	jobs := make(chan job, totalFiles)
	resultsChan := make(chan core.FileResult, totalFiles)

	var wg sync.WaitGroup

	// Spawn worker goroutines
	for w := 0; w < concurrency; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for j := range jobs {
				select {
				case <-ctx.Done():
					return
				default:
				}

				pdfName := strings.TrimSuffix(filepath.Base(j.path), filepath.Ext(j.path))
				splitRes, err := b.extractor.ExtractToDirectory(ctx, j.path, batchTargetDir)
				if err != nil {
					resultsChan <- core.FileResult{
						PDFPath: j.path,
						PDFName: pdfName,
						Success: false,
						Error:   err,
					}
				} else {
					resultsChan <- core.FileResult{
						PDFPath:       j.path,
						PDFName:       pdfName,
						Success:       true,
						ChaptersCount: len(splitRes.Chapters),
						TotalPages:    splitRes.TotalPages,
					}
				}

				if reporter != nil {
					reporter.Increment(filepath.Base(j.path))
				}
			}
		}()
	}

	// Enqueue all files
	for _, f := range pdfFiles {
		jobs <- job{path: f}
	}
	close(jobs)

	// Wait for workers to complete
	go func() {
		wg.Wait()
		close(resultsChan)
		if reporter != nil {
			reporter.Finish()
		}
	}()

	var allResults []core.FileResult
	processedCount := 0
	failedCount := 0

	for res := range resultsChan {
		allResults = append(allResults, res)
		if res.Success {
			processedCount++
		} else {
			failedCount++
		}
	}

	b.generateBatchMasterIndex(batchTargetDir, batchName, allResults, time.Since(startTime))

	return &core.BatchResult{
		BatchName:       batchName,
		TargetDirectory: batchTargetDir,
		TotalFiles:      totalFiles,
		ProcessedFiles:  processedCount,
		FailedFiles:     failedCount,
		Results:         allResults,
		Duration:        time.Since(startTime),
	}, nil
}

func (b *ConcurrentBatchEngine) generateBatchMasterIndex(
	batchDir string,
	batchName string,
	results []core.FileResult,
	duration time.Duration,
) {
	var sb strings.Builder

	cleanName := strings.ReplaceAll(batchName, "_", " ")
	cleanName = strings.ReplaceAll(cleanName, "-", " ")

	sb.WriteString(fmt.Sprintf("# Batch Library: %s\n\n", cleanName))
	sb.WriteString(fmt.Sprintf("Concurrent batch processing completed in %s.\n\n", duration.Round(time.Millisecond)))
	sb.WriteString("---\n\n")
	sb.WriteString("## Extracted Documents Index\n\n")
	sb.WriteString("| # | Document Name | Total Chapters | Total Pages | Folder Path |\n")
	sb.WriteString("| :- | :--- | :--- | :--- | :--- |\n")

	idx := 1
	for _, r := range results {
		if r.Success {
			sb.WriteString(fmt.Sprintf("| **%02d** | %s | %d Chapters | %d Pages | [`%s/`](./%s/README.md) |\n",
				idx, r.PDFName, r.ChaptersCount, r.TotalPages, r.PDFName, r.PDFName))
			idx++
		}
	}

	if len(results)-idx+1 > 0 {
		sb.WriteString("\n### Failed Extractions\n")
		for _, r := range results {
			if !r.Success {
				sb.WriteString(fmt.Sprintf("- **%s**: %v\n", r.PDFName, r.Error))
			}
		}
	}

	sb.WriteString("\n---\n")
	sb.WriteString(fmt.Sprintf("Generated by ytpMD [pdf2md] on %s\n", time.Now().Format("2006-01-02 15:04:05")))

	masterReadme := filepath.Join(batchDir, "README.md")
	_ = os.WriteFile(masterReadme, []byte(sb.String()), 0644)
}
