package extractor

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/devops/pdf2md/pkg/models"
	"github.com/devops/pdf2md/pkg/ui"
	"github.com/devops/pdf2md/pkg/validator"
)

// ProcessBatchConcurrently runs concurrent worker goroutines to process PDF files in parallel.
func (e *PDFExtractor) ProcessBatchConcurrently(
	pdfFiles []string,
	targetBaseDir string,
	batchName string,
	concurrency int,
) (*models.BatchResult, error) {
	if len(pdfFiles) == 0 {
		return nil, fmt.Errorf("no PDF files provided for batch processing")
	}

	startTime := time.Now()

	// Default batch name to "batch" if empty
	if strings.TrimSpace(batchName) == "" {
		batchName = "batch"
	}

	// Destination directory: ~/Documents/ytp24/<batch_name>/
	cleanBaseDir := validator.ExpandPath(targetBaseDir)
	batchTargetDir := filepath.Join(cleanBaseDir, batchName)
	if err := os.MkdirAll(batchTargetDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create batch directory '%s': %w", batchTargetDir, err)
	}

	if concurrency <= 0 {
		concurrency = runtime.NumCPU()
		if concurrency < 2 {
			concurrency = 2
		}
		if concurrency > 8 {
			concurrency = 8
		}
	}

	totalFiles := len(pdfFiles)
	bar := ui.NewProgressBar(totalFiles, "Converting Batch")

	type job struct {
		path string
	}

	jobs := make(chan job, totalFiles)
	resultsChan := make(chan models.FileResult, totalFiles)

	var wg sync.WaitGroup

	// Spawn worker goroutines
	for w := 0; w < concurrency; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for j := range jobs {
				pdfName := strings.TrimSuffix(filepath.Base(j.path), filepath.Ext(j.path))
				
				// Extract to dedicated chapter folder under batchTargetDir
				splitRes, err := e.ExtractToDirectory(j.path, batchTargetDir)
				if err != nil {
					resultsChan <- models.FileResult{
						PDFPath: j.path,
						PDFName: pdfName,
						Success: false,
						Error:   err,
					}
				} else {
					resultsChan <- models.FileResult{
						PDFPath:       j.path,
						PDFName:       pdfName,
						Success:       true,
						ChaptersCount: len(splitRes.Chapters),
						TotalPages:    splitRes.TotalPages,
					}
				}

				bar.Increment(filepath.Base(j.path))
			}
		}()
	}

	// Enqueue all files
	for _, f := range pdfFiles {
		jobs <- job{path: f}
	}
	close(jobs)

	// Wait for workers to finish in a separate goroutine
	go func() {
		wg.Wait()
		close(resultsChan)
		bar.Finish()
	}()

	var allResults []models.FileResult
	processedCount := 0
	failedCount := 0

	for res := range resultsChan {
		allResults = append(allResults, res)
		if res.Success {
			processedCount++
		} else {
			failedCount++
		}
	}

	// Generate Master Batch README.md Index
	e.generateBatchMasterIndex(batchTargetDir, batchName, allResults, time.Since(startTime))

	return &models.BatchResult{
		BatchName:       batchName,
		TargetDirectory: batchTargetDir,
		TotalFiles:      totalFiles,
		ProcessedFiles:  processedCount,
		FailedFiles:     failedCount,
		Results:         allResults,
		Duration:        time.Since(startTime),
	}, nil
}

func (e *PDFExtractor) generateBatchMasterIndex(
	batchDir string,
	batchName string,
	results []models.FileResult,
	duration time.Duration,
) {
	var sb strings.Builder

	cleanName := strings.ReplaceAll(batchName, "_", " ")
	cleanName = strings.ReplaceAll(cleanName, "-", " ")

	sb.WriteString(fmt.Sprintf("# Batch Library: %s\n\n", cleanName))
	sb.WriteString(fmt.Sprintf("Concurrent batch processing completed in %s.\n\n", duration.Round(time.Millisecond)))
	sb.WriteString("---\n\n")
	sb.WriteString("## Extracted Documents Index\n\n")
	sb.WriteString("| # | Document Name | Total Chapters | Total Pages | Folder Path |\n")
	sb.WriteString("| :- | :--- | :--- | :--- | :--- |\n")

	idx := 1
	for _, r := range results {
		if r.Success {
			sb.WriteString(fmt.Sprintf("| **%02d** | %s | %d Chapters | %d Pages | [`%s/`](./%s/README.md) |\n",
				idx, r.PDFName, r.ChaptersCount, r.TotalPages, r.PDFName, r.PDFName))
			idx++
		}
	}

	if len(results)-idx+1 > 0 {
		sb.WriteString("\n### Failed Extractions\n")
		for _, r := range results {
			if !r.Success {
				sb.WriteString(fmt.Sprintf("- **%s**: %v\n", r.PDFName, r.Error))
			}
		}
	}

	sb.WriteString("\n---\n")
	sb.WriteString(fmt.Sprintf("Generated by ytpMD [pdf2md] on %s\n", time.Now().Format("2006-01-02 15:04:05")))

	masterReadme := filepath.Join(batchDir, "README.md")
	_ = os.WriteFile(masterReadme, []byte(sb.String()), 0644)
}
